# Summary of Unit 1La tarea consiste en realizar un portafolio de evidencia que compruebe que se ha aprendido a realizar cada uno de los temas listados en el Syllabus, en la Unidad 1. 

Para esto se utilizarán las 3 tablas contenidas en el dataset del INEGI. 
Se deberá desarrollar en Python, en una Jupyter Notebook, la cual se deberá subir como entregable para este assignment.

# Data Import

In [2]:
# Importando librería pandas abreviada como pd.
import pandas as pd

## Dataset Distrito

In [3]:
# Importando los tres datasets alamacenandolos en diferentes variables (Lo haré en diferentes celdas).
distrito = pd.read_csv("C:/Users/marit/OneDrive/Programming/UPY programming stuff/UPY DATA PREPROCESSING/INEGI Task resources/INE_DISTRITO_2020.CSV", encoding='latin-1')
# Tuve un pequeño problema aquí con el path y su decoding, pero lo arreglé con esto: encoding='latin-1'. 
# Aparentemente por el idioma del dataset o algo dentro de sus bytes no estaba funcionando mi código, pero con esta cosita ya funcionó.

In [4]:
# Usando un print para desplegar la tabla.
print(distrito)

     ENTIDAD         NOM_ENT   DISTRITO INDIGENA      COMPLEJIDA  POBTOT  \
0          1   Aguascalientes         1       NO      Disperso 1  482911
1          1   Aguascalientes         2       NO   Concentrado 1  486085
2          1   Aguascalientes         3       NO   Concentrado 2  456611
3          2  Baja California         1       NO   Concentrado 2  485628
4          2  Baja California         2       NO   Concentrado 1  396169
..       ...              ...       ...      ...             ...     ...
295       31          Yucatán         5       SI      Disperso 1  440998
296       32        Zacatecas         1       NO      Disperso 1  401248
297       32        Zacatecas         2       NO  Muy Disperso 1  382209
298       32        Zacatecas         3       NO      Disperso 2  388643
299       32        Zacatecas         4       NO      Disperso 1  450038

     POBFEM  POBMAS  P_0A2  P_0A2_F  ...  VPH_TELEF  VPH_CEL  VPH_INTER  \
0    245249  237662  27689    13802  ...      32683   110208      59381
1    249098  236987  24904    12319  ...      51688   126004      84830
2    234577  222034  19271     9483  ...      63447   123683      91792
3    240417  245211  19179     9563  ...      70615   141300      97720
4    197545  198624  11110     5479  ...      82630   119147      97297
..      ...     ...    ...      ...  ...        ...      ...        ...
295  221243  219755  22989    11341  ...       9970    92325      36036
296  204384  196864  23355    11498  ...      29959    89927      48632
297  195915  186294  20205    10044  ...      34309    88813      44615
298  198960  189683  19795     9818  ...      38288    89258      53611
299  231821  218217  25078    12460  ...      35496   104816      58087

     VPH_STVP  VPH_SPMVPI  VPH_CVJ  VPH_SINRTV  VPH_SINLTC  VPH_SINCIN  \
0       45106       19305    14900        2752        8043       54801
1       63907       33974    25751        1651        3813       40681
2       65076       45445    29475        1618        3467       33514
3       72397       48338    29949        4220        5526       44317
4       65908       49026    26747        2815        4302       26120
..        ...         ...      ...         ...         ...         ...
295     64935        5919     2653       10718       22202       73204
296     51412       10315     8034        2495       10197       52570
297     48299        7931     6273        4097       11035       57931
298     57594       15716    10661        3540       10995       47440
299     57032       17694    12654        3111       11089       56240

     VPH_SINTIC
0           985
1           373
2           353
3          1241
4           894
..          ...
295        6014
296        1088
297        1678
298        1340
299        1277

[300 rows x 225 columns]

In [29]:
# Usando la función (columns) para ver todas mis columnas.
distrito.columns

Index(['ENTIDAD', 'NOM_ENT ', 'DISTRITO', 'INDIGENA', 'COMPLEJIDA', 'POBTOT',
       'POBFEM', 'POBMAS', 'P_0A2', 'P_0A2_F',
       ...
       'VPH_TELEF', 'VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI',
       'VPH_CVJ', 'VPH_SINRTV', 'VPH_SINLTC', 'VPH_SINCIN', 'VPH_SINTIC'],
      dtype='object', length=225)

In [6]:
# Usando función (info) para ver más específicaciones de mi dataset.
distrito.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Columns: 225 entries, ENTIDAD to VPH_SINTIC
dtypes: int64(222), object(3)
memory usage: 527.5+ KB

In [40]:
# Ahora usaré la función (dtypes) para ver el tipo de datos de cada columna
distrito.dtypes

ENTIDAD        int64
NOM_ENT       object
DISTRITO       int64
INDIGENA      object
COMPLEJIDA    object
               ...
VPH_CVJ        int64
VPH_SINRTV     int64
VPH_SINLTC     int64
VPH_SINCIN     int64
VPH_SINTIC     int64
Length: 225, dtype: object

## Dataset Entidad

In [8]:
# Importando los tres datasets alamacenandolos en diferentes variables (Lo haré en diferentes celdas).
entidad = pd.read_csv("C:/Users/marit/OneDrive/Programming/UPY programming stuff/UPY DATA PREPROCESSING/INEGI Task resources/INE_ENTIDAD_2020.CSV", encoding='latin-1')
# Tuve un pequeño problema aquí con el path y su decoding, pero lo arreglé con esto: encoding='latin-1'. 
# Aparentemente por el idioma del dataset o algo dentro de sus bytes no estaba funcionando mi código, pero con esta cosita ya funcionó.

In [13]:
# Usando un print para desplegar la tabla.
print(entidad)

    ENT                         NOM_ENT     POBTOT   POBFEM   POBMAS   P_0A2  \
0     1                   Aguascalientes   1425607   728924   696683   71864
1     2                  Baja California   3769020  1868431  1900589  149957
2     3              Baja California Sur    798447   392568   405879   35963
3     4                         Campeche    928363   471424   456939   45541
4     5             Coahuila de Zaragoza   3146771  1583102  1563669  160368
5     6                           Colima    731391   370769   360622   29614
6     7                          Chiapas   5543828  2837881  2705947  334055
7     8                        Chihuahua   3741869  1888047  1853822  163950
8     9                 Ciudad de México   9209944  4805017  4404927  267151
9    10                          Durango   1832650   927784   904866   95793
10   11                       Guanajuato   6166934  3170480  2996454  313928
11   12                         Guerrero   3540685  1840073  1700612  197506
12   13                          Hidalgo   3082841  1601462  1481379  134738
13   14                          Jalisco   8348151  4249696  4098455  384145
14   15                           México  16992418  8741123  8251295  724133
15   16              Michoacán de Ocampo   4748846  2442505  2306341  251800
16   17                          Morelos   1971520  1020673   950847   82809
17   18                          Nayarit   1235456   623178   612278   59549
18   19                       Nuevo León   5784442  2893492  2890950  258166
19   20                           Oaxaca   4132148  2157305  1974843  205460
20   21                           Puebla   6583278  3423163  3160115  339025
21   22                        Querétaro   2368467  1211647  1156820  108229
22   23                     Quintana Roo   1857985   921206   936779   84393
23   24                  San Luis Potosí   2822255  1449804  1372451  132634
24   25                          Sinaloa   3026943  1532128  1494815  139403
25   26                           Sonora   2944840  1472643  1472197  124294
26   27                          Tabasco   2402598  1228927  1173671  118339
27   28                       Tamaulipas   3527735  1791595  1736140  154958
28   29                         Tlaxcala   1342977   693083   649894   63959
29   30  Veracruz de Ignacio de la Llave   8062579  4190805  3871774  342746
30   31                          Yucatán   2320898  1180619  1140279  101151
31   32                        Zacatecas   1622138   831080   791058   88433

    P_0A2_F  P_0A2_M   P_0A17   P_3YMAS  ...  VPH_TELEF  VPH_CEL  VPH_INTER  \
0     35604    36260   463335   1352235  ...     147818   359895     236003
1     74010    75947  1061893   3610844  ...     576806  1080169     800189
2     17821    18142   236629    758642  ...      91750   226517     148723
3     22506    23035   286880    878528  ...      68843   218322     114020
4     79095    81273   982841   2980244  ...     372132   824291     519599
5     14483    15131   209402    699821  ...      80251   206736     132395
6    165892   168163  2093426   5181929  ...     159652   944695     292189
7     80466    83484  1137537   3570280  ...     460540  1051045     650546
8    131720   135431  2033581   8933167  ...    1898265  2536523    2084156
9     47204    48589   612346   1733682  ...     137873   434450     215108
10   154709   159219  1965943   5840957  ...     529217  1381668     764350
11    97545    99961  1237843   3328762  ...     252529   715753     298180
12    66770    67968   958875   2944897  ...     210637   727888     332320
13   190072   194073  2531145   7912955  ...    1009963  2134429    1437473
14   357766   366367  5009259  16260058  ...    2123211  4049493    2561525
15   124627   127173  1544594   4493516  ...     333332  1123169     561753
16    40825    41984   568743   1887763  ...     236487   499787     307830
17    29305    30244   394457   1174739  ...     108011   318700     169289
18   127997   130169  1654929   5508144  ...     922162  1537687    1150914
19   101721   103739  1372915   3917300  ...     223680   812319     329811
20   167898   171127  2148335   6238582  ...     490546  1444126     691363
21    53878    54351   700525   2253414  ...     289497   606978     430045
22    41380    43013   543728   1752570  ...     158739   526202     319194
23    65809    66825   879923   2687679  ...     267599   653195     344443
24    68525    70878   902580   2885315  ...     210473   787350     441062
25    61239    63055   876174   2817821  ...     244972   811378     530511
26    58414    59925   781519   2283383  ...     118527   563390     228487
27    76445    78513  1046920   3367123  ...     413157   985027     580241
28    31786    32173   421140   1258093  ...      97434   289686     131845
29   169702   173044  2378935   7716363  ...     635994  1971776     959542
30    49841    51310   666922   2215931  ...     176401   580440     339142
31    43820    44613   544684   1531847  ...     138052   372814     204945

    VPH_STVP  VPH_SPMVPI  VPH_CVJ  VPH_SINRTV  VPH_SINLTC  VPH_SINCIN  \
0     174089       98724    70126        6021       15323      128996
1     618175      384011   216865       41223       38772      293529
2     136538       67961    36197       14508        8675       77223
3     151613       38508    17976       23627       36397      130361
4     443659      195883   124077       17020       46420      332298
5     114164       43881    22695        9173       12085       82366
6     433400       61298    32460      214333      379915      993929
7     481871      282049   179964       42113       64419      432032
8    1290811      957162   568827       46172       77272      561128
9     222785       73099    54664       22071       41801      243750
10    681879      240833   167748       46126      134421      732192
11    343146       56999    28577      125684      172608      599093
12    378326       95701    64475       51691      102005      467376
13   1199700      573528   375678       56399       96948      760439
14   1559564      822048   572663      133777      329132     1769551
15    684146      149704   101530       57579      111766      655580
16    222853       90825    48209       24696       34950      227132
17    178574       60325    35983       20501       28481      167969
18    806584      490746   306104       36729       57505      439479
19    321144       60715    29789      181771      263541      736533
20    539920      213909   129993      102541      207818      939937
21    382086      183742   106431       22702       44358      208004
22    267556      131827    55902       43642       36378      221620
23    347311      128861    83293       43489       90622      388169
24    457908      162367    92477       35425       50477      365642
25    501521      210780   126299       32807       48777      302080
26    276817       66338    31004       54983       96508      404524
27    434549      197140   116590       39790       55012      436801
28    124796       27291    18744       11774       34553      183348
29    914961      268958   133977      183055      342920     1329356
30    306523      129272    60161       33887       67719      283586
31    214337       51656    37622       13243       43316      214181

    VPH_SINTIC
0         1711
1         9582
2         2608
3        12028
4         5754
5         2698
6       151655
7        20158
8        10528
9        12446
10       20559
11       70622
12       26079
13       17553
14       53857
15       23842
16        7724
17        9171
18        9797
19      106502
20       49800
21        9228
22       12239
23       23153
24       12648
25       11895
26       25731
27       11760
28        5272
29       94369
30       16519
31        5383

[32 rows x 222 columns]

In [30]:
# Usando la función (columns) para ver todas mis columnas.
entidad.columns

Index(['ENT', 'NOM_ENT ', 'POBTOT', 'POBFEM', 'POBMAS', 'P_0A2', 'P_0A2_F',
       'P_0A2_M', 'P_0A17', 'P_3YMAS',
       ...
       'VPH_TELEF', 'VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI',
       'VPH_CVJ', 'VPH_SINRTV', 'VPH_SINLTC', 'VPH_SINCIN', 'VPH_SINTIC'],
      dtype='object', length=222)

In [31]:
# Usando función (info) para ver más específicaciones de mi dataset.
entidad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 222 entries, ENT to VPH_SINTIC
dtypes: float64(7), int64(214), object(1)
memory usage: 55.6+ KB

In [41]:
# Ahora usaré la función (dtypes) para ver el tipo de datos de cada columna
entidad.dtypes

ENT            int64
NOM_ENT       object
POBTOT         int64
POBFEM         int64
POBMAS         int64
               ...
VPH_CVJ        int64
VPH_SINRTV     int64
VPH_SINLTC     int64
VPH_SINCIN     int64
VPH_SINTIC     int64
Length: 222, dtype: object

## Dataset Sección

In [10]:
# Importando los tres datasets alamacenandolos en diferentes variables (Lo haré en diferentes celdas).
seccion = pd.read_csv("C:/Users/marit/OneDrive/Programming/UPY programming stuff/UPY DATA PREPROCESSING/INEGI Task resources/INE_SECCION_2020.csv")

In [14]:
# Usando un print para desplegar la tabla.
print(seccion)

         ID  ENTIDAD  DISTRITO  MUNICIPIO  SECCION  TIPO  POBTOT  POBFEM  \
0       118        1         3          1        1     2    2564    1360
1       122        1         3          1        2     2     889     462
2       128        1         3          1        3     2    2003    1057
3       137        1         3          1        4     2    1636     880
4       138        1         3          1        5     2     808     445
...     ...      ...       ...        ...      ...   ...     ...     ...
68801   910       32         4         17     1907     2    1027     527
68802   912       32         4         17     1908     2    1589     832
68803   913       32         4         17     1909     2     269     133
68804  1956       32         3         39     1910     3    2915    1487
68805  1955       32         3         39     1911     3    3868    1982

       POBMAS  P_0A2  ...  VPH_TELEF  VPH_CEL  VPH_INTER  VPH_STVP  \
0        1204     36  ...        698      740        738       659
1         427     27  ...        173      253        195       164
2         946     56  ...        426      621        559       360
3         756     40  ...        311      507        456       330
4         363     14  ...        188      256        233       168
...       ...    ...  ...        ...      ...        ...       ...
68801     500     24  ...        170      290        272       237
68802     757     54  ...        249      461        411       365
68803     136     13  ...         30       73         60        53
68804    1428    162  ...        266      715        411       448
68805    1886    217  ...        288     1027        728       561

       VPH_SPMVPI  VPH_CVJ  VPH_SINRTV  VPH_SINLTC  VPH_SINCIN  VPH_SINTIC
0             615      288           2           1          12           1
1             145       54           4          20          72           2
2             335      184          10           4          74           1
3             329      147          10          11          61           1
4             119       70           4           0          30           0
...           ...      ...         ...         ...         ...         ...
68801         127       87           1           1          16           0
68802         175      124           2           4          37           0
68803          26        9           0           1           9           0
68804          94       80          20          32         305           6
68805         155      123          26          21         257           0

[68806 rows x 226 columns]

In [33]:
# Usando la función (columns) para ver todas mis columnas.
seccion.columns

Index(['ID', 'ENTIDAD', 'DISTRITO', 'MUNICIPIO', 'SECCION', 'TIPO', 'POBTOT',
       'POBFEM', 'POBMAS', 'P_0A2',
       ...
       'VPH_TELEF', 'VPH_CEL', 'VPH_INTER', 'VPH_STVP', 'VPH_SPMVPI',
       'VPH_CVJ', 'VPH_SINRTV', 'VPH_SINLTC', 'VPH_SINCIN', 'VPH_SINTIC'],
      dtype='object', length=226)

In [32]:
# Usando función (info) para ver más específicaciones de mi dataset.
seccion.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68806 entries, 0 to 68805
Columns: 226 entries, ID to VPH_SINTIC
dtypes: float64(7), int64(219)
memory usage: 118.6 MB

In [42]:
# Ahora usaré la función (dtypes) para ver el tipo de datos de cada columna
seccion.dtypes

ID            int64
ENTIDAD       int64
DISTRITO      int64
MUNICIPIO     int64
SECCION       int64
              ...
VPH_CVJ       int64
VPH_SINRTV    int64
VPH_SINLTC    int64
VPH_SINCIN    int64
VPH_SINTIC    int64
Length: 226, dtype: object

# Data Exploration

## Dataset Distrito

In [22]:
# Haciendo una mejor visualización de las primeras 5 filas de (distrito), para un mejor entendimiento.
distrito.head(5)

,ENTIDAD,NOM_ENT,DISTRITO,INDIGENA,COMPLEJIDA,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
0,1,Aguascalientes,1,NO,Disperso 1,482911,245249,237662,27689,13802,...,32683,110208,59381,45106,19305,14900,2752,8043,54801,985
1,1,Aguascalientes,2,NO,Concentrado 1,486085,249098,236987,24904,12319,...,51688,126004,84830,63907,33974,25751,1651,3813,40681,373
2,1,Aguascalientes,3,NO,Concentrado 2,456611,234577,222034,19271,9483,...,63447,123683,91792,65076,45445,29475,1618,3467,33514,353
3,2,Baja California,1,NO,Concentrado 2,485628,240417,245211,19179,9563,...,70615,141300,97720,72397,48338,29949,4220,5526,44317,1241
4,2,Baja California,2,NO,Concentrado 1,396169,197545,198624,11110,5479,...,82630,119147,97297,65908,49026,26747,2815,4302,26120,894

In [23]:
# Haciendo una mejor visualización de las primeras 5 filas de (distrito), para un mejor entendimiento.
distrito.tail(5)

,ENTIDAD,NOM_ENT,DISTRITO,INDIGENA,COMPLEJIDA,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
295,31,Yucatán,5,SI,Disperso 1,440998,221243,219755,22989,11341,...,9970,92325,36036,64935,5919,2653,10718,22202,73204,6014
296,32,Zacatecas,1,NO,Disperso 1,401248,204384,196864,23355,11498,...,29959,89927,48632,51412,10315,8034,2495,10197,52570,1088
297,32,Zacatecas,2,NO,Muy Disperso 1,382209,195915,186294,20205,10044,...,34309,88813,44615,48299,7931,6273,4097,11035,57931,1678
298,32,Zacatecas,3,NO,Disperso 2,388643,198960,189683,19795,9818,...,38288,89258,53611,57594,15716,10661,3540,10995,47440,1340
299,32,Zacatecas,4,NO,Disperso 1,450038,231821,218217,25078,12460,...,35496,104816,58087,57032,17694,12654,3111,11089,56240,1277

In [37]:
# Ahora usaré la función (describe) par ver un resumen estadístico de las columnas numéricas.
distrito.describe()

,ENTIDAD,DISTRITO,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_0A17,P_3YMAS,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,...,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000
mean,16.476667,8.523333,420046.746667,215135.446667,204911.300000,19213.513333,9496.250000,9717.263333,127493.193333,399921.946667,...,43948.500000,102586.326667,61023.976667,50704.353333,22053.803333,13490.333333,5961.840000,10569.646667,50360.680000,2842.903333
std,7.939747,8.140250,59313.093187,29164.659537,30615.940435,5299.359865,2644.642163,2657.387319,29738.510427,55549.440819,...,23738.589838,23770.335349,28015.948755,18184.127490,16788.084461,9722.438409,5506.994917,8768.830746,19899.988623,4000.147364
min,1.000000,1.000000,318965.000000,158800.000000,155137.000000,8193.000000,4105.000000,4088.000000,56738.000000,303546.000000,...,1905.000000,35643.000000,4149.000000,10855.000000,446.000000,311.000000,1109.000000,1141.000000,10638.000000,191.000000
25%,11.000000,3.000000,387111.500000,198327.750000,186982.750000,15602.250000,7671.750000,7953.750000,108026.750000,368224.250000,...,25343.250000,88941.250000,39381.000000,39005.000000,8639.500000,5487.250000,2431.250000,4513.250000,33565.000000,655.250000
50%,15.000000,6.000000,413567.500000,212140.000000,200654.000000,19329.000000,9525.000000,9767.500000,127414.500000,394295.500000,...,39311.000000,99265.500000,60469.500000,48982.000000,17982.500000,11689.500000,3913.500000,7179.500000,49020.000000,1325.000000
75%,22.000000,11.000000,444328.000000,227850.000000,215679.500000,22488.000000,11119.000000,11355.750000,143333.500000,422120.500000,...,60544.750000,113269.750000,79888.000000,62894.750000,33510.750000,20274.000000,7522.000000,13618.250000,66933.750000,3376.750000
max,32.000000,41.000000,840624.000000,415157.000000,425467.000000,49407.000000,24778.000000,24629.000000,297571.000000,790903.000000,...,141364.000000,231546.000000,161786.000000,122608.000000,112039.000000,54473.000000,34094.000000,48980.000000,96021.000000,28351.000000

## Dataset Entidad

In [24]:
# Haciendo una mejor visualización de las primeras 5 filas de (entidad), para un mejor entendimiento.
entidad.head(5)

,ENT,NOM_ENT,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_0A17,P_3YMAS,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
0,1,Aguascalientes,1425607,728924,696683,71864,35604,36260,463335,1352235,...,147818,359895,236003,174089,98724,70126,6021,15323,128996,1711
1,2,Baja California,3769020,1868431,1900589,149957,74010,75947,1061893,3610844,...,576806,1080169,800189,618175,384011,216865,41223,38772,293529,9582
2,3,Baja California Sur,798447,392568,405879,35963,17821,18142,236629,758642,...,91750,226517,148723,136538,67961,36197,14508,8675,77223,2608
3,4,Campeche,928363,471424,456939,45541,22506,23035,286880,878528,...,68843,218322,114020,151613,38508,17976,23627,36397,130361,12028
4,5,Coahuila de Zaragoza,3146771,1583102,1563669,160368,79095,81273,982841,2980244,...,372132,824291,519599,443659,195883,124077,17020,46420,332298,5754

In [25]:
# Haciendo una mejor visualización de las últimas 5 filas de (entidad), para un mejor entendimiento.
entidad.tail(5)

,ENT,NOM_ENT,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_0A17,P_3YMAS,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
27,28,Tamaulipas,3527735,1791595,1736140,154958,76445,78513,1046920,3367123,...,413157,985027,580241,434549,197140,116590,39790,55012,436801,11760
28,29,Tlaxcala,1342977,693083,649894,63959,31786,32173,421140,1258093,...,97434,289686,131845,124796,27291,18744,11774,34553,183348,5272
29,30,Veracruz de Ignacio de la Llave,8062579,4190805,3871774,342746,169702,173044,2378935,7716363,...,635994,1971776,959542,914961,268958,133977,183055,342920,1329356,94369
30,31,Yucatán,2320898,1180619,1140279,101151,49841,51310,666922,2215931,...,176401,580440,339142,306523,129272,60161,33887,67719,283586,16519
31,32,Zacatecas,1622138,831080,791058,88433,43820,44613,544684,1531847,...,138052,372814,204945,214337,51656,37622,13243,43316,214181,5383

In [36]:
# Ahora usaré la función (describe) par ver un resumen estadístico de las columnas numéricas.
entidad.describe()

,ENT,POBTOT,POBFEM,POBMAS,P_0A2,P_0A2_F,P_0A2_M,P_0A17,P_3YMAS,P_3YMAS_F,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
count,32.000000,3.200000e+01,3.200000e+01,3.200000e+01,32.000000,32.000000,32.000000,3.200000e+01,3.200000e+01,3.200000e+01,...,3.200000e+01,3.200000e+01,3.200000e+01,3.200000e+01,32.000000,32.000000,32.00000,32.000000,3.200000e+01,32.000000
mean,16.500000,3.937938e+06,2.016895e+06,1.921043e+06,180126.687500,89027.343750,91099.343750,1.195249e+06,3.749268e+06,1.923580e+06,...,4.120172e+05,9.617468e+05,5.720998e+05,4.753533e+05,206754.406250,126471.875000,55892.25000,99090.437500,4.721314e+05,26652.218750
std,9.380832,3.278009e+06,1.692778e+06,1.585771e+06,140571.778417,69526.362605,71046.518307,9.556157e+05,3.138489e+06,1.623865e+06,...,4.789176e+05,8.002486e+05,5.556387e+05,3.509774e+05,221027.441636,142447.140796,53997.15945,99664.849459,3.750266e+05,34202.848731
min,1.000000,7.313910e+05,3.707690e+05,3.606220e+05,29614.000000,14483.000000,15131.000000,2.094020e+05,6.998210e+05,3.553050e+05,...,6.884300e+04,2.067360e+05,1.140200e+05,1.141640e+05,27291.000000,17976.000000,6021.00000,8675.000000,7.722300e+04,1711.000000
25%,8.750000,1.851651e+06,9.261395e+05,9.288008e+05,87423.000000,43210.000000,44213.000000,5.627282e+05,1.747848e+06,8.765620e+05,...,1.453765e+05,4.834528e+05,2.341240e+05,2.228360e+05,65078.000000,36143.500000,22544.25000,38178.250000,2.197602e+05,9213.750000
50%,16.500000,3.054892e+06,1.557615e+06,1.488097e+06,137070.500000,67647.500000,69423.000000,9.307275e+05,2.915106e+06,1.481704e+06,...,2.407295e+05,7.576190e+05,3.417925e+05,3.802060e+05,130549.500000,76709.500000,40506.50000,56258.500000,3.769055e+05,12342.500000
75%,24.250000,4.947592e+06,2.541349e+06,2.406242e+06,253391.500000,125469.500000,127922.000000,1.572178e+06,4.665619e+06,2.401582e+06,...,4.680415e+05,1.090919e+06,6.607502e+05,5.594838e+05,220640.000000,130989.000000,55337.00000,104445.250000,6.132148e+05,24314.250000
max,32.000000,1.699242e+07,8.741123e+06,8.251295e+06,724133.000000,357766.000000,366367.000000,5.009259e+06,1.626006e+07,8.379157e+06,...,2.123211e+06,4.049493e+06,2.561525e+06,1.559564e+06,957162.000000,572663.000000,214333.00000,379915.000000,1.769551e+06,151655.000000

## Dataset Sección

In [27]:
# Haciendo una mejor visualización de las últimas 5 filas de (seccion), para un mejor entendimiento.
seccion.head(5)

,ID,ENTIDAD,DISTRITO,MUNICIPIO,SECCION,TIPO,POBTOT,POBFEM,POBMAS,P_0A2,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
0,118,1,3,1,1,2,2564,1360,1204,36,...,698,740,738,659,615,288,2,1,12,1
1,122,1,3,1,2,2,889,462,427,27,...,173,253,195,164,145,54,4,20,72,2
2,128,1,3,1,3,2,2003,1057,946,56,...,426,621,559,360,335,184,10,4,74,1
3,137,1,3,1,4,2,1636,880,756,40,...,311,507,456,330,329,147,10,11,61,1
4,138,1,3,1,5,2,808,445,363,14,...,188,256,233,168,119,70,4,0,30,0

In [26]:
# Haciendo una mejor visualización de las últimas 5 filas de (seccion), para un mejor entendimiento.
seccion.tail(5)

,ID,ENTIDAD,DISTRITO,MUNICIPIO,SECCION,TIPO,POBTOT,POBFEM,POBMAS,P_0A2,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
68801,910,32,4,17,1907,2,1027,527,500,24,...,170,290,272,237,127,87,1,1,16,0
68802,912,32,4,17,1908,2,1589,832,757,54,...,249,461,411,365,175,124,2,4,37,0
68803,913,32,4,17,1909,2,269,133,136,13,...,30,73,60,53,26,9,0,1,9,0
68804,1956,32,3,39,1910,3,2915,1487,1428,162,...,266,715,411,448,94,80,20,32,305,6
68805,1955,32,3,39,1911,3,3868,1982,1886,217,...,288,1027,728,561,155,123,26,21,257,0

In [38]:
# Ahora usaré la función (describe) par ver un resumen estadístico de las columnas numéricas.
seccion.describe()

,ID,ENTIDAD,DISTRITO,MUNICIPIO,SECCION,TIPO,POBTOT,POBFEM,POBMAS,P_0A2,...,VPH_TELEF,VPH_CEL,VPH_INTER,VPH_STVP,VPH_SPMVPI,VPH_CVJ,VPH_SINRTV,VPH_SINLTC,VPH_SINCIN,VPH_SINTIC
count,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,...,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000,68806.000000
mean,2257.964044,16.860753,7.599672,48.347223,1604.947417,2.633608,1831.439467,938.008255,893.430050,83.772026,...,191.618667,447.284510,266.069195,221.074746,96.155931,58.818475,25.993547,46.084004,219.576229,12.394748
std,2900.314005,8.286648,7.310902,66.196288,1356.936637,0.879179,2230.152980,1131.936249,1101.468199,120.385041,...,287.621981,599.038712,422.913592,312.252411,215.150048,131.652889,45.582430,70.449895,265.982451,31.553548
min,1.000000,1.000000,1.000000,1.000000,1.000000,2.000000,0.000000,-6.000000,-6.000000,-6.000000,...,-6.000000,-6.000000,-6.000000,-6.000000,-6.000000,-6.000000,-6.000000,-6.000000,-6.000000,-6.000000
25%,608.000000,10.000000,3.000000,10.000000,558.000000,2.000000,771.000000,396.000000,373.000000,26.000000,...,35.000000,184.000000,60.000000,79.000000,5.000000,4.000000,5.000000,9.000000,70.000000,1.000000
50%,1349.000000,15.000000,5.000000,30.000000,1255.000000,2.000000,1293.000000,668.000000,626.000000,50.000000,...,126.000000,318.000000,180.000000,152.000000,44.000000,27.000000,12.000000,22.000000,138.000000,3.000000
75%,2485.000000,24.000000,10.000000,59.000000,2275.000000,4.000000,2109.000000,1084.000000,1024.000000,97.000000,...,245.000000,501.000000,317.000000,256.000000,106.000000,65.000000,28.000000,54.000000,279.000000,11.000000
max,50511.000000,32.000000,41.000000,570.000000,6637.000000,4.000000,49997.000000,24568.000000,25429.000000,3214.000000,...,6627.000000,14499.000000,11373.000000,9049.000000,6737.000000,3843.000000,1164.000000,1384.000000,6336.000000,1038.000000

# Data Cleaning

## Dataset Distrito

In [45]:
# Ahora averiguaré si el dataset tiene filas duplicadas.
distrito.drop_duplicates(inplace=True)
distrito.shape

(300, 225)

Como podemos apreciar el dataset aparenta no tener filas duplicadas, ya que contiene la misma forma que en nuestra primera instancia de la función (shape).

In [46]:
# Vamos a crear una copia de nuestro dataset para ver si tiene valores nulos.
distrito_cp = distrito.copy()

In [47]:
# Usaremos (dropna) para remover las filas con valores nulos.
distrito_cp.dropna(axis = 0 , inplace=True ) 
# Ahora checaremos con (info).
distrito_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Columns: 225 entries, ENTIDAD to VPH_SINTIC
dtypes: int64(222), object(3)
memory usage: 527.5+ KB

Ahora si comprobamos con la cantidad de valores de nuestro primer instancia de la función (info) podemos percatarnos de que los valores son los mimos por ende no hay valores duplicados.

## Dataset Entidad

In [49]:
# Ahora averiguaré si el dataset tiene filas duplicadas.
entidad.drop_duplicates(inplace=True)
entidad.shape

(32, 222)

Como podemos apreciar el dataset aparenta no tener filas duplicadas, ya que contiene la misma forma que en nuestra primera instancia de la función (shape).

In [50]:
# Vamos a crear una copia de nuestro dataset para ver si tiene valores nulos.
entidad_cp = entidad.copy()

In [51]:
# Usaremos (dropna) para remover las filas con valores nulos.
entidad_cp.dropna(axis = 0 , inplace=True ) 
# Ahora checaremos con (info).
entidad_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Columns: 222 entries, ENT to VPH_SINTIC
dtypes: float64(7), int64(214), object(1)
memory usage: 55.6+ KB

Ahora si comprobamos con la cantidad de valores de nuestro primer instancia de la función (info) podemos percatarnos de que los valores son los mimos por ende no hay valores duplicados.

## Dataset Sección

In [52]:
# Ahora averiguaré si el dataset tiene filas duplicadas.
seccion.drop_duplicates(inplace=True)
seccion.shape

(68806, 226)

Como podemos apreciar el dataset aparenta no tener filas duplicadas, ya que contiene la misma forma que en nuestra primera instancia de la función (shape).

In [53]:
# Vamos a crear una copia de nuestro dataset para ver si tiene valores nulos.
seccion_cp = seccion.copy()

In [54]:
# Usaremos (dropna) para remover las filas con valores nulos.
seccion_cp.dropna(axis = 0 , inplace=True ) 
# Ahora checaremos con (info).
seccion_cp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68806 entries, 0 to 68805
Columns: 226 entries, ID to VPH_SINTIC
dtypes: float64(7), int64(219)
memory usage: 118.6 MB

Ahora si comprobamos con la cantidad de valores de nuestro primer instancia de la función (info) podemos percatarnos de que los valores son los mimos por ende no hay valores duplicados.

# Data Transformation

## Dataset Distrito

## Dataset Entidad

## Dataset Sección